/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Danny;

/**
 *
 * @author Usuario Estandar
 */
public class Cita extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cita
     */
    public Cita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLfechacita = new javax.swing.JLabel();
        jLnombrecita = new javax.swing.JLabel();
        jLcedulacliente = new javax.swing.JLabel();
        txtnombrecita = new javax.swing.JTextField();
        txtcedulacita = new javax.swing.JTextField();
        jLhoracita = new javax.swing.JLabel();
        txthoracita = new javax.swing.JTextField();
        btncita = new javax.swing.JButton();
        jLcita = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLfechacita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLfechacita.setText("Fecha Cita");

        jLnombrecita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLnombrecita.setText("Nombre Cliente");

        jLcedulacliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLcedulacliente.setText("Cedula Cliente");

        jLhoracita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLhoracita.setText("Hora Cita");

        btncita.setText("AGENDAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnombrecita)
                            .addComponent(jLcedulacliente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombrecita)
                            .addComponent(txtcedulacita, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLfechacita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addComponent(jLhoracita)
                        .addGap(18, 18, 18)
                        .addComponent(txthoracita, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncita, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLfechacita)
                    .addComponent(jLhoracita)
                    .addComponent(txthoracita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombrecita)
                    .addComponent(txtnombrecita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(btncita, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcedulacliente)
                    .addComponent(txtcedulacita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 510, 200));

        jLcita.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLcita.setText("AGENDAR CITA");
        getContentPane().add(jLcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncita;
    private javax.swing.JLabel jLcedulacliente;
    private javax.swing.JLabel jLcita;
    private javax.swing.JLabel jLfechacita;
    private javax.swing.JLabel jLhoracita;
    private javax.swing.JLabel jLnombrecita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcedulacita;
    private javax.swing.JTextField txthoracita;
    private javax.swing.JTextField txtnombrecita;
    // End of variables declaration//GEN-END:variables
}
