/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Danny;

/**
 *
 * @author Usuario Estandar
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLclicedula = new javax.swing.JLabel();
        jLclinombre = new javax.swing.JLabel();
        jLcliapellido = new javax.swing.JLabel();
        jLclisexo = new javax.swing.JLabel();
        rbtnH = new javax.swing.JRadioButton();
        rbtnM = new javax.swing.JRadioButton();
        jLclifechanacimiento = new javax.swing.JLabel();
        txtclicedula = new javax.swing.JTextField();
        txtclinombre = new javax.swing.JTextField();
        txtcliapellido = new javax.swing.JTextField();
        jLclitelefono = new javax.swing.JLabel();
        jLclicorreo = new javax.swing.JLabel();
        jLclidireccion = new javax.swing.JLabel();
        txtclitelefono = new javax.swing.JTextField();
        txtclicorreo = new javax.swing.JTextField();
        txtclidireccion = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLcligenero = new javax.swing.JLabel();
        jCcligenero = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLbuscarcliente = new javax.swing.JLabel();
        txtbuscarcliente = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRAR CLIENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 290, 30));

        jLclicedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLclicedula.setText("Cedula");

        jLclinombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLclinombre.setText("Nombre");

        jLcliapellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLcliapellido.setText("Apellido");

        jLclisexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLclisexo.setText("Sexo");

        rbtnH.setText("H");

        rbtnM.setText("M");

        jLclifechanacimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLclifechanacimiento.setText("Fecha Nacimiento");

        jLclitelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLclitelefono.setText("Telefono");

        jLclicorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLclicorreo.setText("Correo");

        jLclidireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLclidireccion.setText("Direccion");

        btnregistrar.setText("REGISTRAR");

        btncancelar.setText("CANCELAR");

        jLcligenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLcligenero.setText("Genero");

        jCcligenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otros", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLclifechanacimiento)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnH)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLclicedula)
                                            .addComponent(jLclinombre)
                                            .addComponent(jLcliapellido))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtclicedula, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(txtclinombre)
                                            .addComponent(txtcliapellido)))
                                    .addComponent(jLclisexo))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLclitelefono)
                                            .addComponent(jLclicorreo))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtclitelefono)
                                            .addComponent(txtclicorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLclidireccion)
                                            .addComponent(jLcligenero))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCcligenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtclidireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btncancelar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLclicedula)
                    .addComponent(txtclicedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLclitelefono)
                    .addComponent(txtclitelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLclinombre)
                    .addComponent(txtclinombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLclicorreo)
                    .addComponent(txtclicorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcliapellido)
                    .addComponent(txtcliapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLclidireccion)
                    .addComponent(txtclidireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLclisexo)
                    .addComponent(jLcligenero)
                    .addComponent(jCcligenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnH)
                    .addComponent(rbtnM))
                .addGap(18, 18, 18)
                .addComponent(jLclifechanacimiento)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 550, 330));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Sexo", "Fecha. N", "Telefono", "Correo", "Direccion", "Genero"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLbuscarcliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLbuscarcliente.setText("Buscar Cliente");

        btnbuscar.setText("BUSCAR");

        btneliminar.setText("ELIMINAR");

        btnmodificar.setText("MODIFICAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btneliminar)
                        .addGap(126, 126, 126)
                        .addComponent(btnmodificar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLbuscarcliente)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnbuscar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbuscarcliente)
                    .addComponent(txtbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneliminar)
                    .addComponent(btnmodificar))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 650, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox<String> jCcligenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbuscarcliente;
    private javax.swing.JLabel jLcliapellido;
    private javax.swing.JLabel jLclicedula;
    private javax.swing.JLabel jLclicorreo;
    private javax.swing.JLabel jLclidireccion;
    private javax.swing.JLabel jLclifechanacimiento;
    private javax.swing.JLabel jLcligenero;
    private javax.swing.JLabel jLclinombre;
    private javax.swing.JLabel jLclisexo;
    private javax.swing.JLabel jLclitelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbtnH;
    private javax.swing.JRadioButton rbtnM;
    private javax.swing.JTextField txtbuscarcliente;
    private javax.swing.JTextField txtcliapellido;
    private javax.swing.JTextField txtclicedula;
    private javax.swing.JTextField txtclicorreo;
    private javax.swing.JTextField txtclidireccion;
    private javax.swing.JTextField txtclinombre;
    private javax.swing.JTextField txtclitelefono;
    // End of variables declaration//GEN-END:variables
}
